import Head from 'next/head'
import { Inter } from '@next/font/google'
import Sidebar from 'components/Sidebar'
import {Feed} from '../components/Feed'
import Widgets from '../components/Widgets'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Social App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
       <main className='flex min-h-screen max-w-7xl mx-auto '>
        {/* sidebar */}
        <Sidebar />

        {/* feed */}
        <Feed />

        {/* widget */}
        <Widgets />


        {/*modal  */}


       </main>
    </>
  )
}
